addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - uuid-dev
    - libssl-dev

language: crystal

env:
 - ZMQ="4.1.4" SODIUM="1.0.5"

before_install:
 - export CXX=g++-4.9
 - export CC=gcc-4.9
 - mkdir ldlocal
 - export LDHACK=`pwd`/ldlocal
 - export LDFLAGS=-L$LDHACK/lib
 - export CFLAGS=-I$LDHACK/include
 - export LD_RUN_PATH=$LDHACK/lib
 - export LD_LIBRARY_PATH=$LDHACK/lib
 - export LIBRARY_PATH=$LDHACK/lib
 - export PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig
 - echo $PKG_CONFIG_PATH
 - wget https://github.com/zeromq/zeromq4-1/releases/download/v$ZMQ/zeromq-$ZMQ.tar.gz
 - tar xzvf zeromq-$ZMQ.tar.gz
 - '[ -z "$SODIUM" ] || wget https://download.libsodium.org/libsodium/releases/libsodium-$SODIUM.tar.gz'
 - '[ -z "$SODIUM" ] || tar xzvf libsodium-$SODIUM.tar.gz'
 - '[ -z "$SODIUM" ] || cd libsodium-$SODIUM'
 - '[ -z "$SODIUM" ] || ./autogen.sh'
 - '[ -z "$SODIUM" ] || ./configure --prefix=$LDHACK'
 - '[ -z "$SODIUM" ] || make'
 - '[ -z "$SODIUM" ] || make install'
 - '[ -z "$SODIUM" ] || cd ..'
 - '[ -z "$SODIUM" ] || export LIBS=-lsodium && export sodium_CFLAGS=$CFLAGS && export sodium_LIBS=$LDFLAGS'
 - cd zeromq-$ZMQ
 - ./autogen.sh
 - if [[ -z "$SODIUM" ]]; then ./configure --prefix=$LDHACK; else ./configure --prefix=$LDHACK --with-libsodium=$LDHACK; fi
 - make
 - make install
 - cd ..

script:
  crystal spec
